### ISSUE TITLE
for ocp4 on fedora

### ISSUE THREAD

**Issue by debianmaster** [Jooho/jhouse_openshift#2]
>  just fyi on fresh fedora 29 machine i had to do following to make ocp4 install progress
```
yum install unzip python3-netaddr libvirt-python git -y 
ansible-playbook config_kvm.yml -e ansible_python_interpreter=/usr/bin/python3
````

**Comment by Jooho** [comment]
Thanks I will write it on README file

**Comment by Jooho** [comment]
This looks .. it is because python 3 become default from fedora 29.

**Comment by Jooho** [comment]
I tested and I realized that python 3 is not default in fedora 29. I believe your environment use python3 as a default. That's why it failed.
